---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest


inputs:
  - name: hello_hapi
  - name: dependency-cache


run:
  path: hello_api/ci/scripts/run_tests.sh
