---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest


inputs:
  - name: hello_api
  - name: dependency-cache


run:
  path: concourse-project/ci/scripts/run_tests.sh
